Repository AelinXYZ/aelin-frontend-v2, pull requests merged in 2022-06, with the labels that each got.

#440 Vest Section - Add empty state
  src/components/vest/VestDealTokens.tsx
Labels: enhancement

#423 History Section - Add empty state
  src/components/history/DealsAccepted.tsx
  src/components/history/DealsFunded.tsx
  src/components/history/DealsSponsored.tsx
  src/components/history/Deposits.tsx
  src/components/history/Vests.tsx
  src/components/history/Withdraws.tsx
  src/components/history/common/TableWrapper.tsx
Labels: enhancement

#449 [BUG] added totalUsersInvested, totalUsersAccepted, totalUsersRejected to fragments
  src/queries/pools/fragments.ts
Labels: bug

#445 Fix Deadline Bars (Info & Timeline)
  src/components/common/DynamicDeadline.tsx
  src/components/pools/actions/AcceptDeal.tsx
  src/components/pools/common/Timeline.tsx
  src/components/pools/deal/DealInformation.tsx
  src/components/pools/deal/VestingInformation.tsx
  src/components/pools/list/List.tsx
  src/components/pools/main/PoolInformation.tsx
  src/components/vest/VestDealTokens.tsx
  src/hooks/aelin/useAelinPoolStatus.ts
  src/utils/date.ts
  types/aelinPool.ts
Labels: bug

#447 (Fix) Showing to many (unnecessary) decimals
  src/components/pools/deal/DealCreateStepInput.tsx
Labels: bug

#453 Responsiveness - Timeline & Sidebar are now initialized as collapsed on Mobile version
  package.json
  src/components/common/CollapsibleBlock.tsx
  yarn.lock
Labels: bug

#455 Responsiveness - Stake page
  src/components/stake/StakeGrid.tsx
Labels: bug

#504 Stake page - Fix AELIN/ETH pool
  src/components/stake/StakeTabContent.tsx
  src/constants/misc.ts
  src/utils/stake/getGelatoStakingRewards.ts
Labels: bug

#519 Sidebar - Fix My Pools empty state
  src/components/sidebar/MyPools.tsx
Labels: bug

#521 Fix deal tokens accepted
  src/hooks/aelin/useAelinPool.tsx
  src/utils/aelinPoolUtils.ts
Labels: bug

#526 Fix L1 Stake Box
  pages/stake.tsx
  src/components/stake/StakeInfo.tsx
  src/components/stake/StakeSection.tsx
Labels: bug

#446 [AELIP-15] Nft collections section
  next.config.js
  pages/pool/create.tsx
  src/components/assets/Verified.tsx
  src/components/pools/whitelist/NftCollectionsSection.tsx
  src/components/pools/whitelist/WhiteListModal.tsx
  src/components/pools/whitelist/addresses/AddressesWhiteList.tsx
  src/components/pools/whitelist/addresses/UploadWhiteListCsv.tsx
  src/components/pools/whitelist/nft/NftCollection.tsx
  src/components/pools/whitelist/nft/NftCollectionAttribute.tsx
  src/components/pools/whitelist/nft/NftCollectionDetails.tsx
  src/components/pools/whitelist/nft/NftCollectionInput.tsx
  src/components/pools/whitelist/nft/NftCollectionsSection.tsx
  src/components/pools/whitelist/nft/NftTypeSection.tsx
  src/components/pools/whitelist/nft/NftWhiteList.tsx
  src/components/pools/whitelist/nft/NftWhiteListProcessSection.tsx
  src/components/pools/whitelist/nft/NftsMinimumAmounts.tsx
  src/components/pools/whitelist/nft/nftWhiteListReducer.tsx
  src/components/pools/whitelist/nft/useNftCollectionList.tsx
  src/hooks/aelin/useAelinCreatePool.tsx
  src/theme/darkTheme.ts
  src/theme/lightTheme.ts
  src/utils/validate/createPool.ts
Labels: enhancement

#535 Fix mainnet buy aelin url
  src/components/layout/Header.tsx
Labels: bug

#536 Disable vest for first aelin pool
  src/components/pools/actions/Vest/Vest.tsx
  src/constants/misc.ts
  src/constants/pool.ts
  src/hooks/aelin/useAelinVestingDeals.tsx
  src/utils/isFirstAelinPool.ts
Labels: bug

#555 Bug/release funds
  src/components/pools/actions/ReleaseFunds.tsx
Labels: bug, High priority
